Доработана фильтрация карты
htmlacademy-javascript/1501599-keksobooking-22 pull request #11
Opened 2021-03-15 12:38 UTC by zakrjv

2021-03-15 12:53 UTC, phwb requested changes

2021-03-15 12:53 UTC, phwb commented on index.html
> +<script src="https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js"></script>
круто что ты умеешь так делать, но предполагалось что ты напишешь сама

2021-03-15 12:53 UTC, phwb commented on js/main.js
> +  setFilterClick(_.debounce(
давай без лодаша )

2021-03-15 13:03 UTC, zakrjv commented on js/main.js
> +  setFilterClick(_.debounce(
Okay x)

2021-03-16 06:20 UTC, phwb approved these changes

2021-03-16 06:20 UTC, merged