Добавлен модуль по генерации объявления
htmlacademy-javascript/1501599-keksobooking-22 pull request #5
Opened 2021-02-22 16:53 UTC by zakrjv

2021-02-23 08:06 UTC, phwb requested changes

2021-02-23 08:06 UTC, phwb commented on js/similar-ads.js
> +ADS_CONTAINER.appendChild(card);
вот это должно быть в main.js, из этого модуля ты просто должна экспортировать функции, а собирать логику воедино в main.js

2021-02-23 08:06 UTC, phwb commented on js/similar-ads.js
> +  const adElement = TEMPLATE_AD.cloneNode(true);
шаблон лучше передать в аргументах

2021-02-23 08:06 UTC, phwb commented on js/similar-ads.js
> +const similarAd = createObject();
объявления тоже нужно создавать в main.js

2021-02-23 08:06 UTC, phwb commented on js/similar-ads.js
> +const TEMPLATE_AD = document.querySelector('#card').content.querySelector('.popup');
и знания о шаблонах тоже должны быть в main.js

2021-02-23 08:07 UTC, phwb commented
если не понятно, то можешь созвониться и я объясню

2021-02-23 15:17 UTC, phwb requested changes

2021-02-23 15:17 UTC, phwb commented on js/main.js
> +const similarAd = createObject();
а зачем ты генерируешь новый объект? у тебя же чуть ниже целый массив генерируется, просто возьми первый элемент

2021-02-23 17:21 UTC, zakrjv commented on js/main.js
> +const similarAd = createObject();
Исправила :)

2021-02-24 03:37 UTC, phwb approved these changes
вот теперь супер

2021-02-24 03:37 UTC, phwb commented on js/main.js
> +const ADS_CONTAINER = document.querySelector('#map-canvas');
не верное именование переменной, в данном случае это не константа, а обычная переменная, следовательно именовать ее нужно так же

тоже самое и с `TEMPLATE_AD`

2021-02-24 03:37 UTC, merged